FROM nginx:alpine

COPY ./app /usr/share/nginx/html

RUN sed -i '/<head>/a <meta name="environment" content="production">' /usr/share/nginx/html/index.html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

